#ifndef ALTA_INTERFACE_H
#define ALTA_INTERFACE_H

#include <string>
#include <fstream>
#include <iostream>

enum sample{

};

void export_altaFormat(std::vector<sample> data){

    std::string OutputStr = "# Generated By Alta_Interface @ Behnam Maneshgar";
    OutputStr += "#DIM 1 1\n";
    OutputStr += "#PARAM_IN  UNKNOWN";
    OutputStr += "#PARAM_OUT UNKNOWN";
    OutputStr += "#ALTA END HEADER";



    return;
}


#endif // ALTA_INTERFACE_H
